// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaegputqyrqcmqsyswvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZWdwdXRxeXJxY21xc3lzd3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMTM0MjgsImV4cCI6MjA1MTY4OTQyOH0.sNw1KpgKZQTSWM3MZdflhopCxMYT_61rWwRAGamI3Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);