// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrbqjzthymraypchvalm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYnFqenRoeW1yYXlwY2h2YWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NDgxNzgsImV4cCI6MjA1MjQyNDE3OH0.ZayXMFEQVLngBWESRpw-NAyuTq7GaOsI0szEB2HSz3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);